services:
  php:
    container_name: lms-php
    build:
      context: ./docker/php
      args:
        uid: 1000
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    depends_on:
      - mysql
  nginx:
    container_name: lms-nginx
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    container_name: lms-mysql
    image: mysql:8.0.0
    restart: always
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    ports:
      - '3308:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}